worker-threads: 4
worker-fs-threads: 2
worker-grpc-threads: 2
logger-level: debug

is-testing: false

server-port: 8080
server-grpc-port: 8081

hello-endpoint: '[::1]:8081'

dbconnection: 'postgresql://simple_db_calls_user:password@localhost:5432/simple_db_calls_db_1'
